python train.py convex \
    -project convex \
    -dataset swat \
    -dataroot 'TEEN/data/swat' \
    -base_mode 'ft_dot' \
    -new_mode 'avg_cos' \
    -lr_base 0.1 \
    -decay 0.0005 \
    -epochs_base 100 \
    -batch_size_base 128 \
    -test_batch_size 128 \
    -schedule Cosine \
    -tmax 100 \
    -gpu '0' \
    -temperature 16 \
    -seed 3409 \
    -csv_path 'data/swat/data_newlabel.csv' \
    -json_path 'data/swat/attack_point.json' \
    -is_pretrain