c:/Users/27220/AppData/Local/miniconda3/envs/python3.8_pytorch1.12.1/python.exe train.py teen `
    -project teen `
    -dataset swat `
    -dataroot 'TEEN/data/swat' `
    -base_mode 'ft_dot' `
    -new_mode 'avg_cos' `
    -lr_base 0.1 `
    -decay 0.0005 `
    -epochs_base 100 `
    -batch_size_base 128 `
    -test_batch_size 80 `
    -schedule Cosine `
    -tmax 100 `
    -gpu '0' `
    -temperature 16 `
    -softmax_t 16 `
    -shift_weight 0.1 `
    -soft_mode 'soft_proto' `
    -seed 3407