python train.py fbo \
    -project fbo \
    -dataset wadi \
    -dataroot 'TEEN/data/wadi' \
    -base_mode 'ft_dot' \
    -new_mode 'avg_cos' \
    -lr_base 0.1 \
    -decay 0.0005 \
    -epochs_base 100 \
    -batch_size_base 128 \
    -test_batch_size 128 \
    -schedule Cosine \
    -tmax 100 \
    -gpu '0' \
    -temperature 16 \
    -multi_proto_num 3 \
    -knn_epoch 50 \
    -alpha1 1 \
    -seed 3414